version: '3.8'

services:
  web:
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - ./frontend/.env
    links:
      - db
    depends_on:
      - db

  db:
    build: ./backend
    restart: always
    volumes:
      - flask-redis:/data
    expose:
      - "6379"

volumes:
  flask-redis: